USE [master]
GO

/****** Object:  Database [DNNSoftware]    Script Date: 06/30/2009 11:48:18 ******/
IF EXISTS ( SELECT  name
            FROM    sys.databases
            WHERE   name = N'DNNSoftware' ) 
    BEGIN
        PRINT 'Drop database'
		ALTER DATABASE [DNNSoftware] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
        DROP DATABASE [DNNSoftware]
    end
GO

/****** Object:  Database [DNNSoftware]    Script Date: 06/29/2009 17:16:38 ******/
CREATE DATABASE [DNNSoftware]
GO
PRINT 'Created database'

ALTER DATABASE [DNNSoftware] SET COMPATIBILITY_LEVEL = 120
GO
PRINT 'Set SQL2012 level'

IF ( 1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled') ) 
    begin
        EXEC [DNNSoftware].[dbo].[sp_fulltext_database] @action = 'enable'
        PRINT 'Full text enabled'
    end
GO

PRINT 'Apply settings'

ALTER DATABASE [DNNSoftware] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DNNSoftware] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DNNSoftware] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DNNSoftware] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DNNSoftware] SET ARITHABORT OFF 
GO

ALTER DATABASE [DNNSoftware] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DNNSoftware] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DNNSoftware] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DNNSoftware] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DNNSoftware] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DNNSoftware] SET CURSOR_DEFAULT GLOBAL 
GO

ALTER DATABASE [DNNSoftware] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DNNSoftware] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DNNSoftware] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DNNSoftware] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DNNSoftware] SET DISABLE_BROKER 
GO

ALTER DATABASE [DNNSoftware] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DNNSoftware] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DNNSoftware] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DNNSoftware] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DNNSoftware] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DNNSoftware] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DNNSoftware] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DNNSoftware] SET READ_WRITE 
GO

ALTER DATABASE [DNNSoftware] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DNNSoftware] SET MULTI_USER 
GO

ALTER DATABASE [DNNSoftware] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DNNSoftware] SET DB_CHAINING OFF 
GO

/****** Object:  User [DotNetNuke]    Script Date: 06/29/2009 17:17:51 ******/
PRINT 'Create user'

USE [DNNSoftware]
GO

CREATE USER [DotNetNuke] FOR LOGIN [DotNetNuke] WITH DEFAULT_SCHEMA= [dbo]
GO

PRINT '[DNNSoftware] >>>>>>> Done!'